services:
  netbot:
    build:
      context: .
    container_name: netbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - NETBOX_TOKEN=${NETBOX_TOKEN}
      - NETBOX_URL=${NETBOX_URL}
      - REDMINE_TOKEN=${REDMINE_TOKEN}
      - REDMINE_URL=${REDMINE_URL}
