services:
  netbot:
    build:
      context: .
    container_name: netbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDMINE_TOKEN=${REDMINE_TOKEN}
      - REDMINE_URL=${REDMINE_URL}
    restart: on-failure:1
    network_mode: host
