[project]
name = "netbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.12",
    "audioop",
    "dateparser>=1.2.1",
    "discord>=2.3.2",
    "humanize>=4.12.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
